export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  WARNING: "ALERT_WARNING",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR"
};

export const userConstants = {
  //--REGISTER--//
  REGISTER_PENDING: "REGISTER_PENDING",
  REGISTER_FULFILLED: "REGISTER_FULFILLED",
  REGISTER_ERROR: "REGISTER_ERROR",

  //--LOGIN--//
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_RESET: "LOGIN_RESET",

  //--AUTH--//
  AUTH_PENDING: "AUTH_PENDING",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",
  AUTH_RESET: "AUTH_RESET",

  //--LOGOUT--//
  LOGOUT_PENDING: "LOGOUT_PENDING",
  LOGOUT_FULFILLED: "LOGOUT_FULFILLED",
  LOGOUT_ERROR: "LOGOUT_ERROR"
};
